id = "ini"
name = "ini"
description = "Support for ini and related config files (ini, conf, cfg, config) and systemd unit files (automount, mount, path, scope, service, slice, socket, swap, target, timer)"
version = "0.0.8"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-ini"

[grammars.ini]
repository = "https://github.com/justinmk/tree-sitter-ini"
commit = "e4018b5176132b4f3c5d6e61cea383f42288d0f5"
